# Importing the librares

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import csv

# Importing the Dataset

In [3]:
#dataset = pd.read_csv('X_trainData_1.csv')
#labels=pd.read_csv('Y_trainData_1.csv')
dataset = pd.read_csv('SMOTE_updated_X_trainData_column_modified_CAP.csv')
#datalabels=pd.read_csv('X_trainData_column_modified_CAP.csv')


#X_train=dataset.iloc[:,:].values

X_train=dataset.iloc[:,:-1].values
#y_train=datalabels.iloc[:,-1].values
y_train=dataset.iloc[:,-1].values

In [4]:
print(X_train)


[[0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]]


In [5]:
print(y_train)

count1=0
count0=0

for n in y_train:
  if n==1:
    count1=count1+1
  else:
    count0=count0+1

print(count1)
print(count0)

[1 1 0 ... 0 0 0]
752
752


In [8]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

#from xgboost import XGBClassifier
#classifier = XGBClassifier()
#classifier.fit(X_train, y_train)

#from sklearn.ensemble import RandomForestClassifier
#classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
#classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

#Predicting Validation set results 

In [9]:
#test_data = pd.read_csv('X_testData_column_modified_PCA_CAP.csv')
test_data = pd.read_csv('X_testData_1_modified.csv')

X_test=test_data.iloc[:,:].values


print(type(X_test))
print(len(X_test))
print(len(X_test[0]))
print(X_test)

<class 'numpy.ndarray'>
1000
219
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
y_pred = classifier.predict_proba(X_test)
#y_pred = classifier.predict(X_test)
#y_pred = ann.predict(X_test)
print(y_pred)

print(type(y_pred))
#y_pred = (y_pred > 0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_validation.reshape(len(y_validation),1)),1))

[[0.00170131 0.99829869]
 [0.01950796 0.98049204]
 [0.00848123 0.99151877]
 ...
 [0.00386342 0.99613658]
 [0.01283611 0.98716389]
 [0.00267442 0.99732558]]
<class 'numpy.ndarray'>


In [ ]:
print(len(y_pred))


1000


In [11]:
submission_data = pd.read_csv('Y_testData_1_nolabels_CAP.csv')

ids=submission_data.iloc[:,:1].values
result=list()
k=0
#print(ids)
#print(y_pred[0])
for i in ids:
  #result.append([ i[0], y_pred[i[0]-1][0] ])
  #result.append([ i[0], y_pred[i[0]-1][0] ])
  #result.append([ i[0], y_pred[k][0] ])
  result.append([ i[0], y_pred[k][1] ])
  k=k+1
  #print(y_pred[i[0]-1][0])
  #print('.')

result.insert(0, ['ID','CAP'])
print(result)

[['ID', 'CAP'], [1, 0.9982986929132598], [2, 0.9804920365780714], [3, 0.9915187714650713], [4, 0.9900003655524225], [5, 0.9931484336175984], [6, 0.9915187714650713], [7, 0.9864855736638161], [8, 0.9809324026668207], [9, 0.9846488265282652], [10, 0.9880282856469824], [11, 0.9863773185181284], [12, 0.9930556005259872], [13, 0.9943043455911899], [14, 0.9509415740785929], [15, 0.9834862763468492], [16, 0.9764134136695878], [17, 0.9974735992911138], [18, 0.9810950551484557], [19, 0.9971703339856262], [20, 0.984259164077616], [21, 0.9809579751014239], [22, 0.9900003655524225], [23, 0.9964256761254645], [24, 0.9957613887293238], [25, 0.9885917905186903], [26, 0.9980665623130407], [27, 0.989285464730636], [28, 0.9915544736008124], [29, 0.9634681043350926], [30, 0.9866151847686724], [31, 0.9948227659011127], [32, 0.8292521607373882], [33, 0.9762843170568455], [34, 0.9895105129823356], [35, 0.6160529596283808], [36, 0.9869176613712627], [37, 0.9864855736638161], [38, 0.9966890333864492], [39, 0.

In [13]:
file = open('CAP_result.csv', 'w+', newline ='') 
  
# writing the data into the file 
with file:     
    write = csv.writer(file) 
    write.writerows(result) 